- name: ping the server
  hosts: frontend
  tasks:
   - name: ping the server
     ansible.builtin.ping:




# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 02-hello-world.yaml
# since we are using host as frontend pass username and password     