- name: install nginx and run
  hosts: frontend
  connection: local
  tasks:
  - name: Install nginx server
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


   